package db.models;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class UserEntityTest {

    //only testing toString-method
    //other methods are autogenerated

    @Test
    public void toStringTest() {
        UserEntity testUser = new UserEntity("Test-User", "12345", (byte) 0);

        String expectedString = "(Test-User, 12345, 0)";

        assertEquals(testUser.toString(), expectedString);

    }
}